#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

for rc in *rc gitconfig Xresources Xmodmap gitconfig tmux.conf; do
  ln -sfv $BASE/$rc ~/.$rc
done

mkdir -p $HOME/.config/nvim
ln -sfv $BASE/vimrc ~/.config/nvim/init.vim

mkdir -p $HOME/.vim/colors
mkdir -p $HOME/.config/nvim//colors
ln -sfv $BASE/night.vim ~/.config/nvim//colors/night.vim

configure_npm_directory() {
  mkdir -p ~/.npm-global
  npm config set prefix '~/.npm-global'
}
