#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

for rc in *rc gitconfig Xresources Xmodmap gitconfig tmux.conf mongorc.js; do
  ln -sfv $BASE/$rc ~/.$rc
done

mkdir -p $HOME/.vim/colors
ln -sfv $BASE/night.vim ~/.vim/colors/night.vim

if [ "$PLATFORM" == Darwin ]; then
  echo "OSX Detected"
  LOCATION=~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
else
  echo "Linux Detected"
  LOCATION=~/.config/sublime-text-3/Packages/User
fi

mkdir -p "$LOCATION"
ln -sfv $BASE/sublime/* "$LOCATION"

configure_npm_directory() {
  mkdir -p ~/.npm-global
  npm config set prefix '~/.npm-global'
}

setup_go_tools() {
  go get golang.org/x/tools/cmd/godoc
  go get -u github.com/nsf/gocode # autocomplete tool
  go install # golang.org/x/tools/cmd/godoc

  go get golang.org/x/mobile/cmd/gomobile
  go get github.com/golang/go # download go core source code
}
